### ISSUE TITLE
filter_on_position won't accept a simple [ra, dec] list

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/DAXA#281]
Edward spotted this issue - I say in the docstring that either a

 "list or nested list (i.e. [r, d] OR [[r1, d1], [r2, d2]])"

can be passed, but that isn't true. Even if there is one coordinate pair you still have to pass it as [[ra, dec]] currently.

@jessicapilling  if you could fix this and include that scenario in the tests that would be great, cheers.

**Comment by jessicapilling** [comment]
I think Edward is looking at an older version of DAXA because I also spotted this when I was initially writing unit tests.
I corrected this bug and did some unit tests for it in my initial unit test branch, which has been merged into main now.

The code added in mission.base is [here](https://github.com/DavidT3/DAXA/blob/master/daxa/mission/base.py#L1292-L1299)

The unit test testing this is [here](https://github.com/DavidT3/DAXA/blob/master/tests/test_erosita.py#L141-L144)
